[package]
name = "dice_and_robots"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "^4"
actix-files = "0.6.6"
tokio = "^1"
serde = { version = "^1", features = ["derive"]}
serde_json = "^1"
